codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      target: 90
    patch: yes
    changes: yes

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
